### ISSUE TITLE
Microservice in monolithic ?

### ISSUE THREAD

**Issue by LeChatErrant** [antoinefamibelle/FreelanceKillerBack#7]
Hi ! I'm a french developer and I love your work <3 Thanks for all you're doing, I'm learning a lot

I was just wondering, in your [user.controller.ts](https://github.com/antoinefamibelle/FreelanceKillerBack/blob/main/src/app/user/user.controller.ts)`), you're using an IMSResponse

IMS stands for Interface Micro Service, are you using micro services or a big monolithic architecture ?

Thanks in advance

_Just a random cat passing by_

**Comment by antoinefamibelle** [comment]
Hello my dear friend ! 
So yes I'm currently using the MS and IMS notation because this project will soon be a micro-service has it is specified in the commit this is only the initialization of the project.  I've setup the project in public so everyone can follow the progression of this one !

Sweet regards,
